### ISSUE TITLE
Scroll Bar Blocks Viewer Count

### ISSUE THREAD

**Issue by ErisNoRNG** [zigamacele/liver#4]
When there are enough selected VTubers to require a scroll bar, the viewer count is partially or completely blocked.

![image](https://github.com/zigamacele/liver/assets/93564882/d6dd02df-0f44-4912-8e55-f5f9f78ad3ca)

![image](https://github.com/zigamacele/liver/assets/93564882/9086bc21-2d02-4c14-ba52-d1749a335711)

**Comment by zigamacele** [comment]
Hello, I removed the scrollbar.
You can wait for chrome to update it automatically or remove the extension and reinstall it again.
